services:
  webapi:
    build:
      context: ./web-api
      dockerfile: Dockerfile
    image: 127.0.0.1:5000/webapi:latest
    # container_name: webapi-xxx
    restart: unless-stopped
    ports:
      - target: 3000
        published: 3000
    deploy:
      replicas: 3
      placement:
        constraints: [node.role == manager]
      update_config:
        parallelism: 2
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s